//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Searcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Searcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        internal static string btnRebuild {
            get {
                return ResourceManager.GetString("btnRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating directories count....
        /// </summary>
        internal static string CalcDirsCount {
            get {
                return ResourceManager.GetString("CalcDirsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t load file!.
        /// </summary>
        internal static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index settings.
        /// </summary>
        internal static string IndexSettings {
            get {
                return ResourceManager.GetString("IndexSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories: {0}  time: {1}s  speed: {2} mb/s.
        /// </summary>
        internal static string ProgressString {
            get {
                return ResourceManager.GetString("ProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect memory.
        /// </summary>
        internal static string Starting_CollectMemory {
            get {
                return ResourceManager.GetString("Starting_CollectMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating engine.
        /// </summary>
        internal static string Starting_CreatingEngine {
            get {
                return ResourceManager.GetString("Starting_CreatingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file data.
        /// </summary>
        internal static string Starting_LoadingFileData {
            get {
                return ResourceManager.GetString("Starting_LoadingFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file names.
        /// </summary>
        internal static string Starting_LoadingFileNames {
            get {
                return ResourceManager.GetString("Starting_LoadingFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to search:.
        /// </summary>
        internal static string TextToSearch {
            get {
                return ResourceManager.GetString("TextToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To big file: {0}!.
        /// </summary>
        internal static string ToBigFile {
            get {
                return ResourceManager.GetString("ToBigFile", resourceCulture);
            }
        }
    }
}
