//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.PluginsShared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PluginsSharedLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PluginsSharedLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.PluginsShared.PluginsSharedLang", typeof(PluginsSharedLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time.
        /// </summary>
        public static string AverageTime {
            get {
                return ResourceManager.GetString("AverageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body:.
        /// </summary>
        public static string Body {
            get {
                return ResourceManager.GetString("Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building....
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t run, because next parameters are invalid:.
        /// </summary>
        public static string CantRunInvalidParams {
            get {
                return ResourceManager.GetString("CantRunInvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation time: {0} ms..
        /// </summary>
        public static string CompilationTimeTemplate {
            get {
                return ResourceManager.GetString("CompilationTimeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure directory path.
        /// </summary>
        public static string ConfigureDirectoryPath {
            get {
                return ResourceManager.GetString("ConfigureDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure double.
        /// </summary>
        public static string ConfigureDouble {
            get {
                return ResourceManager.GetString("ConfigureDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure file path.
        /// </summary>
        public static string ConfigureFilePath {
            get {
                return ResourceManager.GetString("ConfigureFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure guid.
        /// </summary>
        public static string ConfigureGuid {
            get {
                return ResourceManager.GetString("ConfigureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure int.
        /// </summary>
        public static string ConfigureInt {
            get {
                return ResourceManager.GetString("ConfigureInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure item.
        /// </summary>
        public static string ConfigureItem {
            get {
                return ResourceManager.GetString("ConfigureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure string.
        /// </summary>
        public static string ConfigureString {
            get {
                return ResourceManager.GetString("ConfigureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy results to clipboard.
        /// </summary>
        public static string CopyResultsToClipboard {
            get {
                return ResourceManager.GetString("CopyResultsToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ddos.
        /// </summary>
        public static string Ddos {
            get {
                return ResourceManager.GetString("Ddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Entries count: {1}..
        /// </summary>
        public static string EntriesCountTemplate {
            get {
                return ResourceManager.GetString("EntriesCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Cloning unit tests folder.
        /// </summary>
        public static string FinishClonningUnitTestsFolder {
            get {
                return ResourceManager.GetString("FinishClonningUnitTestsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string Format {
            get {
                return ResourceManager.GetString("Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers:.
        /// </summary>
        public static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max time.
        /// </summary>
        public static string MaxTime {
            get {
                return ResourceManager.GetString("MaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min time.
        /// </summary>
        public static string MinTime {
            get {
                return ResourceManager.GetString("MinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors.
        /// </summary>
        public static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading....
        /// </summary>
        public static string Reloading {
            get {
                return ResourceManager.GetString("Reloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests delay:.
        /// </summary>
        public static string RequestsDelay {
            get {
                return ResourceManager.GetString("RequestsDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Time ( Min - Average - Max ).
        /// </summary>
        public static string ResponseTime {
            get {
                return ResourceManager.GetString("ResponseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts package parameters:.
        /// </summary>
        public static string ScriptsPackageParameters {
            get {
                return ResourceManager.GetString("ScriptsPackageParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select script.
        /// </summary>
        public static string SelectSctipt {
            get {
                return ResourceManager.GetString("SelectSctipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources editor.
        /// </summary>
        public static string SourcesEditor {
            get {
                return ResourceManager.GetString("SourcesEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cloning unit tests folder.
        /// </summary>
        public static string StartClonningUnitTestsFolder {
            get {
                return ResourceManager.GetString("StartClonningUnitTestsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistic {
            get {
                return ResourceManager.GetString("Statistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test time.
        /// </summary>
        public static string TestTime {
            get {
                return ResourceManager.GetString("TestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads:.
        /// </summary>
        public static string Threads {
            get {
                return ResourceManager.GetString("Threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout:.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
    }
}
