//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.Automator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AutomatorLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutomatorLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.Automator.AutomatorLang", typeof(AutomatorLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building....
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t run, because next parameters are invalid:.
        /// </summary>
        public static string CantRunInvalidParams {
            get {
                return ResourceManager.GetString("CantRunInvalidParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation time: {0} ms..
        /// </summary>
        public static string CompilationTimeTemplate {
            get {
                return ResourceManager.GetString("CompilationTimeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure directory path.
        /// </summary>
        public static string ConfigureDirectoryPath {
            get {
                return ResourceManager.GetString("ConfigureDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure double.
        /// </summary>
        public static string ConfigureDouble {
            get {
                return ResourceManager.GetString("ConfigureDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure file path.
        /// </summary>
        public static string ConfigureFilePath {
            get {
                return ResourceManager.GetString("ConfigureFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure guid.
        /// </summary>
        public static string ConfigureGuid {
            get {
                return ResourceManager.GetString("ConfigureGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure int.
        /// </summary>
        public static string ConfigureInt {
            get {
                return ResourceManager.GetString("ConfigureInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure item.
        /// </summary>
        public static string ConfigureItem {
            get {
                return ResourceManager.GetString("ConfigureItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure operation.
        /// </summary>
        public static string ConfigureOperation {
            get {
                return ResourceManager.GetString("ConfigureOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure profile.
        /// </summary>
        public static string ConfigureProfile {
            get {
                return ResourceManager.GetString("ConfigureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure script packages.
        /// </summary>
        public static string ConfigureScriptPackages {
            get {
                return ResourceManager.GetString("ConfigureScriptPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure string.
        /// </summary>
        public static string ConfigureString {
            get {
                return ResourceManager.GetString("ConfigureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        public static string Editor {
            get {
                return ResourceManager.GetString("Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File:.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors.
        /// </summary>
        public static string NoErrors {
            get {
                return ResourceManager.GetString("NoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple tool to automate everything what is possible. :).
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automater.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading....
        /// </summary>
        public static string Reloading {
            get {
                return ResourceManager.GetString("Reloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all.
        /// </summary>
        public static string RunAll {
            get {
                return ResourceManager.GetString("RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run script.
        /// </summary>
        public static string RunScript {
            get {
                return ResourceManager.GetString("RunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts package parameters:.
        /// </summary>
        public static string ScriptsPackageParameters {
            get {
                return ResourceManager.GetString("ScriptsPackageParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select script.
        /// </summary>
        public static string SelectSctipt {
            get {
                return ResourceManager.GetString("SelectSctipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources editor.
        /// </summary>
        public static string SourcesEditor {
            get {
                return ResourceManager.GetString("SourcesEditor", resourceCulture);
            }
        }
    }
}
