//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.Encoder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EncoderLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EncoderLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.Encoder.EncoderLang", typeof(EncoderLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert on source changed.
        /// </summary>
        public static string ConvertOnSourceChanged {
            get {
                return ResourceManager.GetString("ConvertOnSourceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode c string.
        /// </summary>
        public static string DecodeCstring {
            get {
                return ResourceManager.GetString("DecodeCstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Html.
        /// </summary>
        public static string DecodeHtml {
            get {
                return ResourceManager.GetString("DecodeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode to base64.
        /// </summary>
        public static string DecodeToBase64 {
            get {
                return ResourceManager.GetString("DecodeToBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Uri.
        /// </summary>
        public static string DecodeUri {
            get {
                return ResourceManager.GetString("DecodeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode c string.
        /// </summary>
        public static string EncodeCstring {
            get {
                return ResourceManager.GetString("EncodeCstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Html.
        /// </summary>
        public static string EncodeHtml {
            get {
                return ResourceManager.GetString("EncodeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode to base64.
        /// </summary>
        public static string EncodeToBase64 {
            get {
                return ResourceManager.GetString("EncodeToBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encode Uri.
        /// </summary>
        public static string EncodeUri {
            get {
                return ResourceManager.GetString("EncodeUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format c-like code (JS,CSS).
        /// </summary>
        public static string FormatClikeCode {
            get {
                return ResourceManager.GetString("FormatClikeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Fql Advanced.
        /// </summary>
        public static string FormatFqlAdvanced {
            get {
                return ResourceManager.GetString("FormatFqlAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Fql Simple.
        /// </summary>
        public static string FormatFqlSimple {
            get {
                return ResourceManager.GetString("FormatFqlSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Html.
        /// </summary>
        public static string FormatHtml {
            get {
                return ResourceManager.GetString("FormatHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format JSON.
        /// </summary>
        public static string FormatJSON {
            get {
                return ResourceManager.GetString("FormatJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format SQL.
        /// </summary>
        public static string FormatSQL {
            get {
                return ResourceManager.GetString("FormatSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Xml.
        /// </summary>
        public static string FormatXml {
            get {
                return ResourceManager.GetString("FormatXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to line.
        /// </summary>
        public static string MinimizeToLine {
            get {
                return ResourceManager.GetString("MinimizeToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easy encode/decode strings and change the formatting for easier reading..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap texts.
        /// </summary>
        public static string SwapTexts {
            get {
                return ResourceManager.GetString("SwapTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clipboard.
        /// </summary>
        public static string ToClipboard {
            get {
                return ResourceManager.GetString("ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception!.
        /// </summary>
        public static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
    }
}
