//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.SqlRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SqlRunnerLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlRunnerLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.SqlRunner.SqlRunnerLang", typeof(SqlRunnerLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch....
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch run.
        /// </summary>
        public static string BatchRun {
            get {
                return ResourceManager.GetString("BatchRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure connection string.
        /// </summary>
        public static string ConfigureConnectionString {
            get {
                return ResourceManager.GetString("ConfigureConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure connection to database.
        /// </summary>
        public static string ConfigureConnectionToDatabase {
            get {
                return ResourceManager.GetString("ConfigureConnectionToDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure operation.
        /// </summary>
        public static string ConfigureOperation {
            get {
                return ResourceManager.GetString("ConfigureOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure profile.
        /// </summary>
        public static string ConfigureProfile {
            get {
                return ResourceManager.GetString("ConfigureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection strings to use.
        /// </summary>
        public static string ConnectionStringsToUse {
            get {
                return ResourceManager.GetString("ConnectionStringsToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string to use by default to run scripts:.
        /// </summary>
        public static string ConnectionStringToUseByDefault {
            get {
                return ResourceManager.GetString("ConnectionStringToUseByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDOS....
        /// </summary>
        public static string Ddos {
            get {
                return ResourceManager.GetString("Ddos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make request to.
        /// </summary>
        public static string MakeRequestTo {
            get {
                return ResourceManager.GetString("MakeRequestTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to build and run any SQL commands. Also you can do DDOS to find performance issues..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Runner.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records affected.
        /// </summary>
        public static string RecordsAffected {
            get {
                return ResourceManager.GetString("RecordsAffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request &apos;{0}&apos; results, time: {1}.
        /// </summary>
        public static string RequestResultsTemplate {
            get {
                return ResourceManager.GetString("RequestResultsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:{0}, status: {1}.
        /// </summary>
        public static string ResultsTemplate1 {
            get {
                return ResourceManager.GetString("ResultsTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body: {0}.
        /// </summary>
        public static string ResultsTemplate2 {
            get {
                return ResourceManager.GetString("ResultsTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run scripts.
        /// </summary>
        public static string RunScripts {
            get {
                return ResourceManager.GetString("RunScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL scripts.
        /// </summary>
        public static string SqlScripts {
            get {
                return ResourceManager.GetString("SqlScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL scripts to execute.
        /// </summary>
        public static string SqlScriptsToExecute {
            get {
                return ResourceManager.GetString("SqlScriptsToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use transaction.
        /// </summary>
        public static string UseTransaction {
            get {
                return ResourceManager.GetString("UseTransaction", resourceCulture);
            }
        }
    }
}
