//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.TeamManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TeamManagerLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TeamManagerLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.TeamManager.TeamManagerLang", typeof(TeamManagerLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add not present days.
        /// </summary>
        public static string AddNotPresentDays {
            get {
                return ResourceManager.GetString("AddNotPresentDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want send emails?.
        /// </summary>
        public static string AreYouWantSendEmails {
            get {
                return ResourceManager.GetString("AreYouWantSendEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignable.
        /// </summary>
        public static string Assignable {
            get {
                return ResourceManager.GetString("Assignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating time report....
        /// </summary>
        public static string CalculatingTimeReport {
            get {
                return ResourceManager.GetString("CalculatingTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file to save report.
        /// </summary>
        public static string ChooseFileToSaveReport {
            get {
                return ResourceManager.GetString("ChooseFileToSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure calendar.
        /// </summary>
        public static string ConfigureCalendar {
            get {
                return ResourceManager.GetString("ConfigureCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure operation.
        /// </summary>
        public static string ConfigureOperation {
            get {
                return ResourceManager.GetString("ConfigureOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure persons.
        /// </summary>
        public static string ConfigurePersons {
            get {
                return ResourceManager.GetString("ConfigurePersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure profile.
        /// </summary>
        public static string ConfigureProfile {
            get {
                return ResourceManager.GetString("ConfigureProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure profiles.
        /// </summary>
        public static string ConfigureProfiles {
            get {
                return ResourceManager.GetString("ConfigureProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure script packages.
        /// </summary>
        public static string ConfigureScriptPackages {
            get {
                return ResourceManager.GetString("ConfigureScriptPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure special days.
        /// </summary>
        public static string ConfigureSpecialDays {
            get {
                return ResourceManager.GetString("ConfigureSpecialDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date from.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string Dates {
            get {
                return ResourceManager.GetString("Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date to.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time report: {0} - {1}.
        /// </summary>
        public static string EmailSubjectTemplate {
            get {
                return ResourceManager.GetString("EmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by time.
        /// </summary>
        public static string FilterByTime {
            get {
                return ResourceManager.GetString("FilterByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter results.
        /// </summary>
        public static string FilterResults {
            get {
                return ResourceManager.GetString("FilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full time report: {0} - {1}.
        /// </summary>
        public static string FullEmailSubjectTemplate {
            get {
                return ResourceManager.GetString("FullEmailSubjectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for current week.
        /// </summary>
        public static string GenerateForCurrentWeek {
            get {
                return ResourceManager.GetString("GenerateForCurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get time report.
        /// </summary>
        public static string GetTimeReport {
            get {
                return ResourceManager.GetString("GetTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide persons without errors.
        /// </summary>
        public static string HidePersonsWithoutErrors {
            get {
                return ResourceManager.GetString("HidePersonsWithoutErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html.
        /// </summary>
        public static string HtmlReport {
            get {
                return ResourceManager.GetString("HtmlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is exchange server.
        /// </summary>
        public static string IsExchange {
            get {
                return ResourceManager.GetString("IsExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is holyday.
        /// </summary>
        public static string IsHolyday {
            get {
                return ResourceManager.GetString("IsHolyday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is smtp server.
        /// </summary>
        public static string IsSmtp {
            get {
                return ResourceManager.GetString("IsSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is working day.
        /// </summary>
        public static string IsWorkingDay {
            get {
                return ResourceManager.GetString("IsWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails of the team members.
        /// </summary>
        public static string MembersEmails {
            get {
                return ResourceManager.GetString("MembersEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People included in the report.
        /// </summary>
        public static string PeopleIncludedInTheReport {
            get {
                return ResourceManager.GetString("PeopleIncludedInTheReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify script path, before set paramters.
        /// </summary>
        public static string PleaseSpecifyScriptPath {
            get {
                return ResourceManager.GetString("PleaseSpecifyScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin to simplify team management..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team manager.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare reports....
        /// </summary>
        public static string PrepareReports {
            get {
                return ResourceManager.GetString("PrepareReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager url:.
        /// </summary>
        public static string ProjectManagerUrl {
            get {
                return ResourceManager.GetString("ProjectManagerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script editor for providers.
        /// </summary>
        public static string ProvidersScriptEditor {
            get {
                return ResourceManager.GetString("ProvidersScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report was automatically generated with &lt;a href=&quot;http://tbox.codeplex.com/&quot;&gt;TBox&lt;/a&gt;. Time:.
        /// </summary>
        public static string ReportFooter {
            get {
                return ResourceManager.GetString("ReportFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report type for user.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send email....
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending full report.
        /// </summary>
        public static string SendingFullReport {
            get {
                return ResourceManager.GetString("SendingFullReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to.
        /// </summary>
        public static string SendTo {
            get {
                return ResourceManager.GetString("SendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server url.
        /// </summary>
        public static string ServerUrl {
            get {
                return ResourceManager.GetString("ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Params....
        /// </summary>
        public static string SetParameters {
            get {
                return ResourceManager.GetString("SetParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script:.
        /// </summary>
        public static string SetScripts {
            get {
                return ResourceManager.GetString("SetScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent.
        /// </summary>
        public static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target process.
        /// </summary>
        public static string TargetProcess {
            get {
                return ResourceManager.GetString("TargetProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target time.
        /// </summary>
        public static string TargetTime {
            get {
                return ResourceManager.GetString("TargetTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plain text.
        /// </summary>
        public static string TextReport {
            get {
                return ResourceManager.GetString("TextReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time report.
        /// </summary>
        public static string TimeReport {
            get {
                return ResourceManager.GetString("TimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send emails.
        /// </summary>
        public static string ToEmail {
            get {
                return ResourceManager.GetString("ToEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ToExcel {
            get {
                return ResourceManager.GetString("ToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected exception.
        /// </summary>
        public static string UnexpectedException {
            get {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator.
        /// </summary>
        public static string Validator {
            get {
                return ResourceManager.GetString("Validator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script editor for validators.
        /// </summary>
        public static string ValidatorsScriptEditor {
            get {
                return ResourceManager.GetString("ValidatorsScriptEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours per day.
        /// </summary>
        public static string WorkingHoursPerDay {
            get {
                return ResourceManager.GetString("WorkingHoursPerDay", resourceCulture);
            }
        }
    }
}
