//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.TextGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextGeneratorLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextGeneratorLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.TextGenerator.TextGeneratorLang", typeof(TextGeneratorLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate clipboard text length.
        /// </summary>
        public static string CalcClipboardTextLength {
            get {
                return ResourceManager.GetString("CalcClipboardTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char to fill when you create table to export data to Excel or etc:.
        /// </summary>
        public static string CharToFillWhenYouCreateTable {
            get {
                return ResourceManager.GetString("CharToFillWhenYouCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate GUID.
        /// </summary>
        public static string GenerateGuid {
            get {
                return ResourceManager.GetString("GenerateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Text.
        /// </summary>
        public static string GenerateText {
            get {
                return ResourceManager.GetString("GenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Text form clipboard.
        /// </summary>
        public static string GenerateTextFormClipboard {
            get {
                return ResourceManager.GetString("GenerateTextFormClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the clipboard text.
        /// </summary>
        public static string LengthOfTheClipboardText {
            get {
                return ResourceManager.GetString("LengthOfTheClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify text length.
        /// </summary>
        public static string PleaseSpecifyTextLength {
            get {
                return ResourceManager.GetString("PleaseSpecifyTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small tool to generate text. Also it helps when you export tables to Excel or OneNote..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text generator.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace chars sequences by tabs.
        /// </summary>
        public static string ReplaceCharsSequensesByTabs {
            get {
                return ResourceManager.GetString("ReplaceCharsSequensesByTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample default text.
        /// </summary>
        public static string SampleDefaultText {
            get {
                return ResourceManager.GetString("SampleDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Replacing.
        /// </summary>
        public static string TextReplacing {
            get {
                return ResourceManager.GetString("TextReplacing", resourceCulture);
            }
        }
    }
}
