//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mnk.TBox.Locales.Localization.Plugins.NUnitRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NUnitRunnerLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NUnitRunnerLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mnk.TBox.Locales.Localization.Plugins.NUnitRunner.NUnitRunnerLang", typeof(NUnitRunnerLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch run....
        /// </summary>
        public static string BatchRun {
            get {
                return ResourceManager.GetString("BatchRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch run for unit tests.
        /// </summary>
        public static string BatchRunForUnitTests {
            get {
                return ResourceManager.GetString("BatchRunForUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t refresh unit tests, please specify libraries to test.
        /// </summary>
        public static string CantRefreshUnitTests {
            get {
                return ResourceManager.GetString("CantRefreshUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check All.
        /// </summary>
        public static string CheckAll {
            get {
                return ResourceManager.GetString("CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloning.
        /// </summary>
        public static string Clonning {
            get {
                return ResourceManager.GetString("Clonning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command to run before tests.
        /// </summary>
        public static string CommandToRunBeforeTests {
            get {
                return ResourceManager.GetString("CommandToRunBeforeTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure libraries with unit tests.
        /// </summary>
        public static string ConfigureLibrariesWithUnitTests {
            get {
                return ResourceManager.GetString("ConfigureLibrariesWithUnitTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure test suites.
        /// </summary>
        public static string ConfigureTestSuites {
            get {
                return ResourceManager.GetString("ConfigureTestSuites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy deep.
        /// </summary>
        public static string CopyDeep {
            get {
                return ResourceManager.GetString("CopyDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to separate folders.
        /// </summary>
        public static string CopyToSeparateFolders {
            get {
                return ResourceManager.GetString("CopyToSeparateFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed:.
        /// </summary>
        public static string Displayed {
            get {
                return ResourceManager.GetString("Displayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors:.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors and failures.
        /// </summary>
        public static string ErrorsAndFailures {
            get {
                return ResourceManager.GetString("ErrorsAndFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed:.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path masks to copy.
        /// </summary>
        public static string FileMasksToCopy {
            get {
                return ResourceManager.GetString("FileMasksToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files not exists:.
        /// </summary>
        public static string FilesNotExists {
            get {
                return ResourceManager.GetString("FilesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder to clone tests.
        /// </summary>
        public static string FolderToCloneTests {
            get {
                return ResourceManager.GetString("FolderToCloneTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework.
        /// </summary>
        public static string Framework {
            get {
                return ResourceManager.GetString("Framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored:.
        /// </summary>
        public static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string Include {
            get {
                return ResourceManager.GetString("Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive:.
        /// </summary>
        public static string Inconclusive {
            get {
                return ResourceManager.GetString("Inconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid:.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multithreading.
        /// </summary>
        public static string Multithreading {
            get {
                return ResourceManager.GetString("Multithreading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nunit dlls to run.
        /// </summary>
        public static string NunitDllsToRun {
            get {
                return ResourceManager.GetString("NunitDllsToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed:.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small tool to run nunit tests in parallel..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUnit tests runner.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process count.
        /// </summary>
        public static string ProcessCount {
            get {
                return ResourceManager.GetString("ProcessCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process mode.
        /// </summary>
        public static string ProcessMode {
            get {
                return ResourceManager.GetString("ProcessMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Admin.
        /// </summary>
        public static string RunAsAdmin {
            get {
                return ResourceManager.GetString("RunAsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as x86.
        /// </summary>
        public static string RunAsx86 {
            get {
                return ResourceManager.GetString("RunAsx86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected item info.
        /// </summary>
        public static string SelectedItemInfo {
            get {
                return ResourceManager.GetString("SelectedItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only failed.
        /// </summary>
        public static string ShowOnlyFailed {
            get {
                return ResourceManager.GetString("ShowOnlyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only failed tests.
        /// </summary>
        public static string ShowOnlyFailedTests {
            get {
                return ResourceManager.GetString("ShowOnlyFailedTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped:.
        /// </summary>
        public static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test delay (s).
        /// </summary>
        public static string StartDelay {
            get {
                return ResourceManager.GetString("StartDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize tests agents.
        /// </summary>
        public static string SynchronizeTestsAgents {
            get {
                return ResourceManager.GetString("SynchronizeTestsAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests.
        /// </summary>
        public static string Tests {
            get {
                return ResourceManager.GetString("Tests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests not run.
        /// </summary>
        public static string TestsNotRun {
            get {
                return ResourceManager.GetString("TestsNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests results.
        /// </summary>
        public static string TestsResults {
            get {
                return ResourceManager.GetString("TestsResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - tests: [ {1} ], failed = [ {2} ], time: {3}.
        /// </summary>
        public static string TestsStateTemplate {
            get {
                return ResourceManager.GetString("TestsStateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test time.
        /// </summary>
        public static string TestTime {
            get {
                return ResourceManager.GetString("TestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text output.
        /// </summary>
        public static string TextOutput {
            get {
                return ResourceManager.GetString("TextOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time:.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck All.
        /// </summary>
        public static string UncheckAll {
            get {
                return ResourceManager.GetString("UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use categories.
        /// </summary>
        public static string UseCategories {
            get {
                return ResourceManager.GetString("UseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use statistic for optimization.
        /// </summary>
        public static string UsePrefetch {
            get {
                return ResourceManager.GetString("UsePrefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
