//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.ProjectMan {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectManLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectManLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.ProjectMan.ProjectManLang", typeof(ProjectManLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply patch.
        /// </summary>
        public static string ApplyPatch {
            get {
                return ResourceManager.GetString("ApplyPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch - *.cmd and *.bat.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch/tag.
        /// </summary>
        public static string BranchTag {
            get {
                return ResourceManager.GetString("BranchTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build:.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build tools pathes.
        /// </summary>
        public static string BuildToolsPathes {
            get {
                return ResourceManager.GetString("BuildToolsPathes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean up.
        /// </summary>
        public static string CleanUp {
            get {
                return ResourceManager.GetString("CleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        public static string Commit {
            get {
                return ResourceManager.GetString("Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure projects directories.
        /// </summary>
        public static string ConfigureProjectsDirectories {
            get {
                return ResourceManager.GetString("ConfigureProjectsDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure solutions folders.
        /// </summary>
        public static string ConfigureSolutionsFolders {
            get {
                return ResourceManager.GetString("ConfigureSolutionsFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create patch.
        /// </summary>
        public static string CreatePatch {
            get {
                return ResourceManager.GetString("CreatePatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string Merge {
            get {
                return ResourceManager.GetString("Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsBuild - *.build.
        /// </summary>
        public static string MsBuild {
            get {
                return ResourceManager.GetString("MsBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to MSBuild:.
        /// </summary>
        public static string PathToMSBuild {
            get {
                return ResourceManager.GetString("PathToMSBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to svn:.
        /// </summary>
        public static string PathToSvn {
            get {
                return ResourceManager.GetString("PathToSvn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify build arguments:.
        /// </summary>
        public static string PleaseSpecifyBuildArguments {
            get {
                return ResourceManager.GetString("PleaseSpecifyBuildArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy way to manage your projects. You can rebuild, work with svn and run it&apos;s scripts from tray..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project manager process projects.
        /// </summary>
        public static string ProjectManagerProcessProjects {
            get {
                return ResourceManager.GetString("ProjectManagerProcessProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild all in debug.
        /// </summary>
        public static string RebuildAllInDebug {
            get {
                return ResourceManager.GetString("RebuildAllInDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild all in release.
        /// </summary>
        public static string RebuildAllInRelease {
            get {
                return ResourceManager.GetString("RebuildAllInRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relocate.
        /// </summary>
        public static string Relocate {
            get {
                return ResourceManager.GetString("Relocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo browser.
        /// </summary>
        public static string RepoBrowser {
            get {
                return ResourceManager.GetString("RepoBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolve.
        /// </summary>
        public static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string Revert {
            get {
                return ResourceManager.GetString("Revert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        public static string ShowLog {
            get {
                return ResourceManager.GetString("ShowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my changes.
        /// </summary>
        public static string ShowMyChanges {
            get {
                return ResourceManager.GetString("ShowMyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all.
        /// </summary>
        public static string UpdateAll {
            get {
                return ResourceManager.GetString("UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update and rebuild all in debug.
        /// </summary>
        public static string UpdateAndRebuildAllInDebug {
            get {
                return ResourceManager.GetString("UpdateAndRebuildAllInDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to revision.
        /// </summary>
        public static string UpdateToRevision {
            get {
                return ResourceManager.GetString("UpdateToRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
