//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.Searcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearcherLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SearcherLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.Searcher.SearcherLang", typeof(SearcherLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you realy want rebuild all indexes?.
        /// </summary>
        public static string AreYouWantRebuild {
            get {
                return ResourceManager.GetString("AreYouWantRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating directories count....
        /// </summary>
        public static string CalcDirsCount {
            get {
                return ResourceManager.GetString("CalcDirsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case sensitive search.
        /// </summary>
        public static string CaseSensitiveSearch {
            get {
                return ResourceManager.GetString("CaseSensitiveSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure file masks to exclude unused items.
        /// </summary>
        public static string ConfigureFileMasksToExcludeUnusedItems {
            get {
                return ResourceManager.GetString("ConfigureFileMasksToExcludeUnusedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure files folders to create index.
        /// </summary>
        public static string ConfigureFilesFoldersToCreateIndex {
            get {
                return ResourceManager.GetString("ConfigureFilesFoldersToCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure files types to create index.
        /// </summary>
        public static string ConfigureFilesTypesToCreateIndex {
            get {
                return ResourceManager.GetString("ConfigureFilesTypesToCreateIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create indexes...
        /// </summary>
        public static string CreateIndexes {
            get {
                return ResourceManager.GetString("CreateIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode comments.
        /// </summary>
        public static string DecodeComments {
            get {
                return ResourceManager.GetString("DecodeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode strings.
        /// </summary>
        public static string DecodeStrings {
            get {
                return ResourceManager.GetString("DecodeStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can&apos;t load file!.
        /// </summary>
        public static string ErrorLoadingFile {
            get {
                return ResourceManager.GetString("ErrorLoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable path:.
        /// </summary>
        public static string ExecutablePath {
            get {
                return ResourceManager.GetString("ExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File masks to exclude.
        /// </summary>
        public static string FileMasksToExclude {
            get {
                return ResourceManager.GetString("FileMasksToExclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File parsing.
        /// </summary>
        public static string FileParsing {
            get {
                return ResourceManager.GetString("FileParsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files:.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and folders to search.
        /// </summary>
        public static string FilesAndFoldersToSearch {
            get {
                return ResourceManager.GetString("FilesAndFoldersToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types:.
        /// </summary>
        public static string FileTypes {
            get {
                return ResourceManager.GetString("FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types to include.
        /// </summary>
        public static string FileTypesToInclude {
            get {
                return ResourceManager.GetString("FileTypesToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill results time:.
        /// </summary>
        public static string FillResultsTime {
            get {
                return ResourceManager.GetString("FillResultsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder:.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders to search.
        /// </summary>
        public static string FoldersToSearch {
            get {
                return ResourceManager.GetString("FoldersToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full text search.
        /// </summary>
        public static string FullTextSearch {
            get {
                return ResourceManager.GetString("FullTextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index settings.
        /// </summary>
        public static string IndexSettings {
            get {
                return ResourceManager.GetString("IndexSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file on select.
        /// </summary>
        public static string LoadFileOnSelect {
            get {
                return ResourceManager.GetString("LoadFileOnSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load file time:.
        /// </summary>
        public static string LoadFileTime {
            get {
                return ResourceManager.GetString("LoadFileTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load indexes...
        /// </summary>
        public static string LoadIndexes {
            get {
                return ResourceManager.GetString("LoadIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to search in the big set of files for words and file names..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searcher.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories: {0}  time: {1}s  speed: {2} kb/s.
        /// </summary>
        public static string ProgressString {
            get {
                return ResourceManager.GetString("ProgressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild indexes....
        /// </summary>
        public static string RebuildIndexes {
            get {
                return ResourceManager.GetString("RebuildIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search count:.
        /// </summary>
        public static string SearchCount {
            get {
                return ResourceManager.GetString("SearchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search mode:.
        /// </summary>
        public static string SearchMode {
            get {
                return ResourceManager.GetString("SearchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results view.
        /// </summary>
        public static string SearchResultsView {
            get {
                return ResourceManager.GetString("SearchResultsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search time:.
        /// </summary>
        public static string SearchTime {
            get {
                return ResourceManager.GetString("SearchTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search type:.
        /// </summary>
        public static string SearchType {
            get {
                return ResourceManager.GetString("SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip comments.
        /// </summary>
        public static string SkipComments {
            get {
                return ResourceManager.GetString("SkipComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect memory.
        /// </summary>
        public static string Starting_CollectMemory {
            get {
                return ResourceManager.GetString("Starting_CollectMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating engine.
        /// </summary>
        public static string Starting_CreatingEngine {
            get {
                return ResourceManager.GetString("Starting_CreatingEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file data.
        /// </summary>
        public static string Starting_LoadingFileData {
            get {
                return ResourceManager.GetString("Starting_LoadingFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading file names.
        /// </summary>
        public static string Starting_LoadingFileNames {
            get {
                return ResourceManager.GetString("Starting_LoadingFileNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to search:.
        /// </summary>
        public static string TextToSearch {
            get {
                return ResourceManager.GetString("TextToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To big file: {0}!.
        /// </summary>
        public static string ToBigFile {
            get {
                return ResourceManager.GetString("ToBigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload indexes...
        /// </summary>
        public static string UnloadIndexes {
            get {
                return ResourceManager.GetString("UnloadIndexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word:.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words:.
        /// </summary>
        public static string Words {
            get {
                return ResourceManager.GetString("Words", resourceCulture);
            }
        }
    }
}
