//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Plugins.Templates {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplatesLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatesLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Plugins.Templates.TemplatesLang", typeof(TemplatesLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure known values.
        /// </summary>
        public static string ConfigureKnownValues {
            get {
                return ResourceManager.GetString("ConfigureKnownValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and Folders.
        /// </summary>
        public static string FilesAndFolders {
            get {
                return ResourceManager.GetString("FilesAndFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files &amp; folders templates settings.
        /// </summary>
        public static string FilesAndFoldersTemplatesSettings {
            get {
                return ResourceManager.GetString("FilesAndFoldersTemplatesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Template.
        /// </summary>
        public static string FillTemplate {
            get {
                return ResourceManager.GetString("FillTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill to clipboard.
        /// </summary>
        public static string FillToClipBoard {
            get {
                return ResourceManager.GetString("FillToClipBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name template (should contains &apos;item&apos;):.
        /// </summary>
        public static string ItemNameTemplate {
            get {
                return ResourceManager.GetString("ItemNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known values:.
        /// </summary>
        public static string KnownValues {
            get {
                return ResourceManager.GetString("KnownValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known values to use on run by default:.
        /// </summary>
        public static string KnownValuesToUseOnRunByDefault {
            get {
                return ResourceManager.GetString("KnownValuesToUseOnRunByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability to create group of files and folders by template. For example you can create localization..
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strings.
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String templates.
        /// </summary>
        public static string StringTemplates {
            get {
                return ResourceManager.GetString("StringTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String templates settings.
        /// </summary>
        public static string StringTemplatesSettings {
            get {
                return ResourceManager.GetString("StringTemplatesSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path:.
        /// </summary>
        public static string TargetPath {
            get {
                return ResourceManager.GetString("TargetPath", resourceCulture);
            }
        }
    }
}
