//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mnk.TBox.Locales.Localization.TBox {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TBoxLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TBoxLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mnk.TBox.Locales.Localization.TBox.TBoxLang", typeof(TBoxLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string Aliases {
            get {
                return ResourceManager.GetString("Aliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Alex H (Mnk) from Brest..
        /// </summary>
        public static string AuthorsInfo {
            get {
                return ResourceManager.GetString("AuthorsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update.
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog:.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Start.
        /// </summary>
        public static string BtnFastStart {
            get {
                return ResourceManager.GetString("BtnFastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send feedback.
        /// </summary>
        public static string BtnFeedback {
            get {
                return ResourceManager.GetString("BtnFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string BtnHelp {
            get {
                return ResourceManager.GetString("BtnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string BtnReload {
            get {
                return ResourceManager.GetString("BtnReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string BtnSettings {
            get {
                return ResourceManager.GetString("BtnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox.
        /// </summary>
        public static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change log.
        /// </summary>
        public static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox was updated, the latest changes:.
        /// </summary>
        public static string ChangeLogTitle {
            get {
                return ResourceManager.GetString("ChangeLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        public static string ClearHistory {
            get {
                return ResourceManager.GetString("ClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure alias.
        /// </summary>
        public static string ConfigureAlias {
            get {
                return ResourceManager.GetString("ConfigureAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure user action.
        /// </summary>
        public static string ConfigureUserAction {
            get {
                return ResourceManager.GetString("ConfigureUserAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create plugins...
        /// </summary>
        public static string CreatePlugins {
            get {
                return ResourceManager.GetString("CreatePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins: Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week:.
        /// </summary>
        public static string DayOfTheWeek {
            get {
                return ResourceManager.GetString("DayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day time:.
        /// </summary>
        public static string DayTime {
            get {
                return ResourceManager.GetString("DayTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose item to configure and click on it..
        /// </summary>
        public static string DefaultMainViewDescription {
            get {
                return ResourceManager.GetString("DefaultMainViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins: Desktop.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins: Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing changelog.
        /// </summary>
        public static string ErrorProcessingChangelog {
            get {
                return ResourceManager.GetString("ErrorProcessingChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Start.
        /// </summary>
        public static string FastStart {
            get {
                return ResourceManager.GetString("FastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can run fast called commands or you own user actions.
        /// </summary>
        public static string FastStartDescription {
            get {
                return ResourceManager.GetString("FastStartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox - feedback.
        /// </summary>
        public static string FeedbackCaption {
            get {
                return ResourceManager.GetString("FeedbackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write some words or ideas about how to improve TBox..
        /// </summary>
        public static string FeedbackMessage {
            get {
                return ResourceManager.GetString("FeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending feedback.
        /// </summary>
        public static string FeedbackProgress {
            get {
                return ResourceManager.GetString("FeedbackProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found new version: {0}, current version is: {1}. Do you want to update TBox?.
        /// </summary>
        public static string FoundNewVersionTemplate {
            get {
                return ResourceManager.GetString("FoundNewVersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global HotKeys are enabled.
        /// </summary>
        public static string GlobalHotKeysAreEnabled {
            get {
                return ResourceManager.GetString("GlobalHotKeysAreEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        public static string GlobalSettings {
            get {
                return ResourceManager.GetString("GlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on cancel.
        /// </summary>
        public static string HideOnCancel {
            get {
                return ResourceManager.GetString("HideOnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide on save.
        /// </summary>
        public static string HideOnSave {
            get {
                return ResourceManager.GetString("HideOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotKeys.
        /// </summary>
        public static string HotKeys {
            get {
                return ResourceManager.GetString("HotKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed under GPLv2 license..
        /// </summary>
        public static string LicenseInfo {
            get {
                return ResourceManager.GetString("LicenseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In development since 2010..
        /// </summary>
        public static string LifeTimeInfo {
            get {
                return ResourceManager.GetString("LifeTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max items in history.
        /// </summary>
        public static string MaxItemsInHistory {
            get {
                return ResourceManager.GetString("MaxItemsInHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check updates.
        /// </summary>
        public static string MenuCheckUpdates {
            get {
                return ResourceManager.GetString("MenuCheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Start....
        /// </summary>
        public static string MenuFastStart {
            get {
                return ResourceManager.GetString("MenuFastStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found.
        /// </summary>
        public static string MessageNoUpdatesFound {
            get {
                return ResourceManager.GetString("MessageNoUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox - new version is available!.
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins: Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the errors directory:.
        /// </summary>
        public static string PathToTheErrorsDirectory {
            get {
                return ResourceManager.GetString("PathToTheErrorsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the mirror directory:.
        /// </summary>
        public static string PathToTheMirrorDirectory {
            get {
                return ResourceManager.GetString("PathToTheMirrorDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store configuration files in the TBox folder.
        /// </summary>
        public static string PortableMode {
            get {
                return ResourceManager.GetString("PortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare....
        /// </summary>
        public static string Prepare {
            get {
                return ResourceManager.GetString("Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes....
        /// </summary>
        public static string ProgressApplyChanges {
            get {
                return ResourceManager.GetString("ProgressApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit....
        /// </summary>
        public static string ProgressExit {
            get {
                return ResourceManager.GetString("ProgressExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish....
        /// </summary>
        public static string ProgressFinish {
            get {
                return ResourceManager.GetString("ProgressFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize....
        /// </summary>
        public static string ProgressInitialize {
            get {
                return ResourceManager.GetString("ProgressInitialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading plugins....
        /// </summary>
        public static string ProgressLoadingPlugins {
            get {
                return ResourceManager.GetString("ProgressLoadingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload plugins settings....
        /// </summary>
        public static string ProgressReloadPluginsSettings {
            get {
                return ResourceManager.GetString("ProgressReloadPluginsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent actions.
        /// </summary>
        public static string RecentActions {
            get {
                return ResourceManager.GetString("RecentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart TBox will be requered to apply changes.
        /// </summary>
        public static string RestartNeeded {
            get {
                return ResourceManager.GetString("RestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Scheduler {
            get {
                return ResourceManager.GetString("Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string Schelduler {
            get {
                return ResourceManager.GetString("Schelduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler is enabled.
        /// </summary>
        public static string ScheldulerIsEnabled {
            get {
                return ResourceManager.GetString("ScheldulerIsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts paths.
        /// </summary>
        public static string ScriptsPaths {
            get {
                return ResourceManager.GetString("ScriptsPaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select menu actions.
        /// </summary>
        public static string SelectMenuActions {
            get {
                return ResourceManager.GetString("SelectMenuActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send error reports.
        /// </summary>
        public static string SendErrorReports {
            get {
                return ResourceManager.GetString("SendErrorReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global settings.
        /// </summary>
        public static string SettingsCaption {
            get {
                return ResourceManager.GetString("SettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can configure global settings of this tool.
        /// </summary>
        public static string SettingsDescription {
            get {
                return ResourceManager.GetString("SettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcuts.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to autorun.
        /// </summary>
        public static string ShortcutToAutorun {
            get {
                return ResourceManager.GetString("ShortcutToAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut to desktop.
        /// </summary>
        public static string ShortcutToDesktop {
            get {
                return ResourceManager.GetString("ShortcutToDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show changelog on update.
        /// </summary>
        public static string ShowChangelogOnUpdate {
            get {
                return ResourceManager.GetString("ShowChangelogOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings by single click on tray icon.
        /// </summary>
        public static string ShowSettingsBySingleClickOnTrayIcon {
            get {
                return ResourceManager.GetString("ShowSettingsBySingleClickOnTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start hidden.
        /// </summary>
        public static string StartHidden {
            get {
                return ResourceManager.GetString("StartHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Plugins.
        /// </summary>
        public static string TabsEnabledPlugins {
            get {
                return ResourceManager.GetString("TabsEnabledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team work settings.
        /// </summary>
        public static string TeamWorkSettings {
            get {
                return ResourceManager.GetString("TeamWorkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help author to improve this tool.
        /// </summary>
        public static string ToolTipFeedback {
            get {
                return ResourceManager.GetString("ToolTipFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBox. Load {0} plugin(s)..
        /// </summary>
        public static string ToolTipTemplate {
            get {
                return ResourceManager.GetString("ToolTipTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update disabled items....
        /// </summary>
        public static string UpdateDisabledItems {
            get {
                return ResourceManager.GetString("UpdateDisabledItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update from shared folder.
        /// </summary>
        public static string UpdateFromSharedFolder {
            get {
                return ResourceManager.GetString("UpdateFromSharedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval:.
        /// </summary>
        public static string UpdateInterval {
            get {
                return ResourceManager.GetString("UpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usability.
        /// </summary>
        public static string Usability {
            get {
                return ResourceManager.GetString("Usability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPU for UI render.
        /// </summary>
        public static string UseGPUForUIRender {
            get {
                return ResourceManager.GetString("UseGPUForUIRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User actions.
        /// </summary>
        public static string UserActions {
            get {
                return ResourceManager.GetString("UserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use tray menu with icons.
        /// </summary>
        public static string UseTrayMenuWithIcons {
            get {
                return ResourceManager.GetString("UseTrayMenuWithIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.{1}.
        /// </summary>
        public static string VersionTemplate {
            get {
                return ResourceManager.GetString("VersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins: Web.
        /// </summary>
        public static string Web {
            get {
                return ResourceManager.GetString("Web", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site:.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
